settings:
  title: 'Server Status'
  url: '' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: cloudflare-com
    name: CDN
    description: Cloudflare CDN
    url: 'https://www.cloudflare.com/'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: health-check-ryben-dev-gateway
    name: Server Gateway
    description: Reverse Proxy Service
    url: 'https://health-check.ryben.dev'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: plex-ryben-dev
    name: Plex Server
    url: 'https://plex.ryben.dev/web/index.html'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: dash-ryben-dev
    name: Plex Dashboard
    description: Monitoring Plex Server Connections
    url: 'https://dash.ryben.dev/'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: health-check-ryben-dev-main
    name: Plex Storage
    description: Availability of Main Plex Content
    url: 'https://health-check.ryben.dev/main'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: health-check-ryben-dev-anime
    name: Anime Storage
    description: Availability of Anime Content
    url: 'https://health-check.ryben.dev/anime'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: plex-img-ryben-dev
    name: Movie Poster CDN
    url: 'https://plex-img.ryben.dev/'
    method: GET
    expectStatus: 404
    followRedirect: true

  - id: i-ryben.dev
    name: File Sharing CDN
    description: i.ryben.dev
    url: 'https://i.ryben.dev/test'
    method: GET
    expectStatus: 404
    followRedirect: true
